### ISSUE TITLE
Test whether issuer matches 

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-oidc-tests#2]
NSS has [a bug](https://github.com/solid/node-solid-server/issues/1609) that makes it incompatible (as an IDP) with CSS (as a resource server).

This test suite could test for it.

**Comment by acoburn** [comment]
This would fit under a category of tests that would test the discovery resource (`/.well-known/openid-configuration`) and compare the `issuer` value with the `iss` claim in the resulting tokens. If those don't align, that would be a failure.

**Comment by RubenVerborgh** [comment]
> NSS has [a bug](https://github.com/solid/node-solid-server/issues/1609) that makes it incompatible (as an IDP) with CSS (as a resource server).

How did this slip through the cracks though?
https://github.com/solid/test-suite claims full IDP compatibility for NSS.

There should be an issue on that test suite then too, I presume.

I'm asking specifically because, to my understanding, that test suite relies on NSS IDP capabilities (and specifically the instance deployed at solidcommunity.net) for a fair chunk of its tests, casting doubt over some or all of the reported scores. Which is one other reason why we should be very careful with such reports, if they turn out to be based on incorrect assumptions.

**Comment by acoburn** [comment]
This condition is tested in https://github.com/solid/solid-oidc-tests/blob/c08c3f83e6213ee4228c361665e53fec1145c13a/js/solid-oidc-test-suite.js#L81-L85
